AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Environment:
      Variables:
        CHANNEL_SECRET: ""
        CHANNEL_TOKEN: ""
        DYNAMODB_REGION: "ap-northeast-1"
        DYNAMODB_TABLE: "Diary"

Resources:
  LineDiaryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: line-diary/
      Handler: line-diary
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /line
            Method: POST
      Policies: AmazonDynamoDBFullAccess

  LineNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: line-notify/
      Handler: line-notify
      Tracing: Active
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(* 13 * * ? *)
      Policies: AmazonDynamoDBFullAccess
